export const defaultThemes = [
  {
    name: "Midnight",
    config: {
      background: "#0c0c0e",
      cardBg: "#131316",
      textColor: "#f0eff4",
      mutedColor: "#8a8998",
      accentColor: "#9b7ef8",
      borderColor: "rgba(255,255,255,0.07)",
      buttonStyle: "filled",
      fontFamily: "Inter",
    },
  },
  {
    name: "Pure White",
    config: {
      background: "#ffffff",
      cardBg: "#f5f5f5",
      textColor: "#111111",
      mutedColor: "#888888",
      accentColor: "#333333",
      borderColor: "#eeeeee",
      buttonStyle: "filled",
      fontFamily: "Inter",
    },
  },
  {
    name: "Gold Luxe",
    config: {
      background: "#0e0b06",
      cardBg: "#1a1408",
      textColor: "#f0e8d0",
      mutedColor: "#7a6a4a",
      accentColor: "#c9a96e",
      borderColor: "rgba(201,169,110,0.2)",
      buttonStyle: "filled",
      fontFamily: "Inter",
    },
  },
  {
    name: "Ocean Blue",
    config: {
      background: "#0a1628",
      cardBg: "#0f2035",
      textColor: "#e0f0ff",
      mutedColor: "#6b8db5",
      accentColor: "#5b9cf6",
      borderColor: "rgba(91,156,246,0.15)",
      buttonStyle: "filled",
      fontFamily: "Inter",
    },
  },
  {
    name: "Neon Pink",
    config: {
      background: "#0e0812",
      cardBg: "#1a0f1f",
      textColor: "#f0e0f5",
      mutedColor: "#9b7ab0",
      accentColor: "#ff6b9d",
      borderColor: "rgba(255,107,157,0.15)",
      buttonStyle: "glow",
      fontFamily: "Inter",
    },
  },
  {
    name: "Forest",
    config: {
      background: "#0a120a",
      cardBg: "#0f1a0f",
      textColor: "#e0f0e0",
      mutedColor: "#6b8b6b",
      accentColor: "#4ecb8d",
      borderColor: "rgba(78,203,141,0.15)",
      buttonStyle: "filled",
      fontFamily: "Inter",
    },
  },
  {
    name: "Sunset",
    config: {
      background: "#120a08",
      cardBg: "#1f120e",
      textColor: "#f5e8e0",
      mutedColor: "#b08b70",
      accentColor: "#ff8c42",
      borderColor: "rgba(255,140,66,0.15)",
      buttonStyle: "filled",
      fontFamily: "Inter",
    },
  },
  {
    name: "Minimal Gray",
    config: {
      background: "#f8f8f8",
      cardBg: "#ffffff",
      textColor: "#222222",
      mutedColor: "#999999",
      accentColor: "#555555",
      borderColor: "#e5e5e5",
      buttonStyle: "outlined",
      fontFamily: "Inter",
    },
  },
  {
    name: "Cyberpunk",
    config: {
      background: "#0a0a0a",
      cardBg: "#111111",
      textColor: "#00ff9f",
      mutedColor: "#00cc7f",
      accentColor: "#ff00ff",
      borderColor: "rgba(0,255,159,0.2)",
      buttonStyle: "neon",
      fontFamily: "DM Mono",
    },
  },
  {
    name: "Warm Cream",
    config: {
      background: "#faf5ef",
      cardBg: "#ffffff",
      textColor: "#2d2a26",
      mutedColor: "#8a8070",
      accentColor: "#c9a96e",
      borderColor: "rgba(45,42,38,0.1)",
      buttonStyle: "filled",
      fontFamily: "Inter",
    },
  },
] as const;

export type ThemeConfig = (typeof defaultThemes)[number]["config"];
